http://localhost:5001

###
http://localhost:5001/api/users/test

###
http://localhost:5001/api/posts/test
###
http://localhost:5001/api/profile/test
###
POST http://localhost:5001/api/users/register
Content-Type: application/json

{
  "name":"danilo",
  "email":"danilocordeiro.ti@gmail.com",
  "password":"123456",
  "password_confirmation":"123456"
}
###
POST http://localhost:5001/api/users/login
Content-Type: application/json

{
  "email":"danilocordeiro.ti@gmail.com",
  "password":"123456"
}
###

http://localhost:5001/api/users/current
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViM2ViZWFjZTRkOTIzNTcxYWQyM2IzOCIsIm5hbWUiOiJEYW5pbG8iLCJhdmF0YXIiOiIvL3d3dy5ncmF2YXRhci5jb20vYXZhdGFyLzJjNWM2ZDg1ZjM1NjEzZWViODk3MTAxNDc4ZTQ1NjA2P3M9MjAwJnI9cGcmZD1tbSIsImlhdCI6MTUzMTQ1MTA1MCwiZXhwIjoxNTMxNDU0NjUwfQ.ejms1wMj-2Wl_iMpNrRsWufTRwauCdO5MQY7rfmYySg

###
###teste validation fields
POST http://localhost:5001/api/users/register
Content-Type: application/json

{
  "name":"po",
  "email":"gkgjjgk@kokok.com",
  "password":"1234568",
  "password_confirmation":"1234568"
}
###
http://localhost:5001/api/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViM2ViZWFjZTRkOTIzNTcxYWQyM2IzOCIsIm5hbWUiOiJEYW5pbG8iLCJhdmF0YXIiOiIvL3d3dy5ncmF2YXRhci5jb20vYXZhdGFyLzJjNWM2ZDg1ZjM1NjEzZWViODk3MTAxNDc4ZTQ1NjA2P3M9MjAwJnI9cGcmZD1tbSIsImlhdCI6MTUzMTQ1MTA1MCwiZXhwIjoxNTMxNDU0NjUwfQ.ejms1wMj-2Wl_iMpNrRsWufTRwauCdO5MQY7rfmYySg

###
POST http://localhost:5001/api/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViM2ViZWFjZTRkOTIzNTcxYWQyM2IzOCIsIm5hbWUiOiJEYW5pbG8iLCJhdmF0YXIiOiIvL3d3dy5ncmF2YXRhci5jb20vYXZhdGFyLzJjNWM2ZDg1ZjM1NjEzZWViODk3MTAxNDc4ZTQ1NjA2P3M9MjAwJnI9cGcmZD1tbSIsImlhdCI6MTUzMTQ1MTA1MCwiZXhwIjoxNTMxNDU0NjUwfQ.ejms1wMj-2Wl_iMpNrRsWufTRwauCdO5MQY7rfmYySg

{
  "handle":"dandan",
  "status":"Developer",
  "skills":"HTML,CSS,JS,Ruby",
  "company":"oriedroc",
  "twitter":"jijiji.om",
  "facebook":"fa.com/dan"
}

###
http://localhost:5001/api/profile/handle/dandan
Content-Type: application/json

###
http://localhost:5001/api/profile/user/5b3ebeace4d923571ad23b388
Content-Type: application/json
###
http://localhost:5001/api/profile/all
Content-Type: application/json
###
POST http://localhost:5001/api/profile/experience
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViM2ViZWFjZTRkOTIzNTcxYWQyM2IzOCIsIm5hbWUiOiJEYW5pbG8iLCJhdmF0YXIiOiIvL3d3dy5ncmF2YXRhci5jb20vYXZhdGFyLzJjNWM2ZDg1ZjM1NjEzZWViODk3MTAxNDc4ZTQ1NjA2P3M9MjAwJnI9cGcmZD1tbSIsImlhdCI6MTUzMTQ1NDc3OSwiZXhwIjoxNTMxNDU4Mzc5fQ.Mke3WWw9xXSwYzNhopO7NnNiNkyo2wuG3RCZ6jT0RoI

{
  "title":"Developer",
  "company":"Indra",
  "from":"2009-02-15"
}
###
POST http://localhost:5001/api/profile/education
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViM2ViZWFjZTRkOTIzNTcxYWQyM2IzOCIsIm5hbWUiOiJEYW5pbG8iLCJhdmF0YXIiOiIvL3d3dy5ncmF2YXRhci5jb20vYXZhdGFyLzJjNWM2ZDg1ZjM1NjEzZWViODk3MTAxNDc4ZTQ1NjA2P3M9MjAwJnI9cGcmZD1tbSIsImlhdCI6MTUzMTQ1NDc3OSwiZXhwIjoxNTMxNDU4Mzc5fQ.Mke3WWw9xXSwYzNhopO7NnNiNkyo2wuG3RCZ6jT0RoI

{
  "school":"IFF",
  "degree":"SI",
  "fieldofstudy":"Finaças",
  "from":"2009-02-15"
}

###
DELETE http://localhost:5001/api/profile/experience/5b482b0924a4c220449b326e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViM2ViZWFjZTRkOTIzNTcxYWQyM2IzOCIsIm5hbWUiOiJEYW5pbG8iLCJhdmF0YXIiOiIvL3d3dy5ncmF2YXRhci5jb20vYXZhdGFyLzJjNWM2ZDg1ZjM1NjEzZWViODk3MTAxNDc4ZTQ1NjA2P3M9MjAwJnI9cGcmZD1tbSIsImlhdCI6MTUzMTQ1NDc3OSwiZXhwIjoxNTMxNDU4Mzc5fQ.Mke3WWw9xXSwYzNhopO7NnNiNkyo2wuG3RCZ6jT0RoI

###
DELETE http://localhost:5001/api/profile/education/5b482b76a125ee208dc6d475
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViM2ViZWFjZTRkOTIzNTcxYWQyM2IzOCIsIm5hbWUiOiJEYW5pbG8iLCJhdmF0YXIiOiIvL3d3dy5ncmF2YXRhci5jb20vYXZhdGFyLzJjNWM2ZDg1ZjM1NjEzZWViODk3MTAxNDc4ZTQ1NjA2P3M9MjAwJnI9cGcmZD1tbSIsImlhdCI6MTUzMTQ1NDc3OSwiZXhwIjoxNTMxNDU4Mzc5fQ.Mke3WWw9xXSwYzNhopO7NnNiNkyo2wuG3RCZ6jT0RoI

###
DELETE http://localhost:5001/api/profile/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViM2ViZWFjZTRkOTIzNTcxYWQyM2IzOCIsIm5hbWUiOiJEYW5pbG8iLCJhdmF0YXIiOiIvL3d3dy5ncmF2YXRhci5jb20vYXZhdGFyLzJjNWM2ZDg1ZjM1NjEzZWViODk3MTAxNDc4ZTQ1NjA2P3M9MjAwJnI9cGcmZD1tbSIsImlhdCI6MTUzMTQ1NDc3OSwiZXhwIjoxNTMxNDU4Mzc5fQ.Mke3WWw9xXSwYzNhopO7NnNiNkyo2wuG3RCZ6jT0RoI

###
POST http://localhost:5001/api/posts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViNDlkOWNjNDc3YTlmMWRlMmQ3ODQyYyIsIm5hbWUiOiJkYW5pbG8iLCJhdmF0YXIiOiIvL3d3dy5ncmF2YXRhci5jb20vYXZhdGFyLzJjNWM2ZDg1ZjM1NjEzZWViODk3MTAxNDc4ZTQ1NjA2P3M9MjAwJnI9cGcmZD1tbSIsImlhdCI6MTUzMTU2NjU1MSwiZXhwIjoxNTMxNTcwMTUxfQ.FY6wcpG79vfE9yFpdrEQt_FrUwhwhUdLCori5v0SvBI
 
{
  "text":"Eshjdhs sjdks sdjhlsk sjdlsd sdljsd"
}

###
http://localhost:5001/api/posts
Content-Type: application/json

###
http://localhost:5001/api/posts/5b49db21cbef711fa9bcb875
Content-Type: application/json

###
DELETE http://localhost:5001/api/posts/5b49db21cbef711fa9bcb875
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViNDlkOWNjNDc3YTlmMWRlMmQ3ODQyYyIsIm5hbWUiOiJkYW5pbG8iLCJhdmF0YXIiOiIvL3d3dy5ncmF2YXRhci5jb20vYXZhdGFyLzJjNWM2ZDg1ZjM1NjEzZWViODk3MTAxNDc4ZTQ1NjA2P3M9MjAwJnI9cGcmZD1tbSIsImlhdCI6MTUzMTU3MTY4MSwiZXhwIjoxNTMxNTc1MjgxfQ.bDglwo545yY3FSrYao2OzlJk_uINPh8MKyotz-Z82Ig
